# Generated by Django 5.0.2 on 2024-03-16 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_alter_categoryoffer_category_and_more'),
        ('store', '0022_rename_aprroved_seller_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryoffer',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoryoffers', to='store.category'),
        ),
        migrations.AlterField(
            model_name='productoffer',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productoffers', to='store.product'),
        ),
    ]
