# Generated by Django 5.0.2 on 2024-03-23 04:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_alter_categoryoffer_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryoffer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
