# Generated by Django 5.0.2 on 2024-03-19 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('country', models.CharField(default='US', max_length=255, verbose_name='Country')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('sku', models.CharField(max_length=255, verbose_name='SKU')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_date', models.DateTimeField(db_index=True, verbose_name='date')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Price')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Value')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_report.client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_report.product')),
            ],
        ),
    ]
