# Generated by Django 5.0.2 on 2024-03-25 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_report', '0002_salesreportgenerator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalesReportGenerator',
        ),
    ]
