# Generated by Django 5.0.2 on 2024-02-28 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_address_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='user_profile',
            new_name='user',
        ),
    ]
