# Generated by Django 5.0.2 on 2024-03-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_address_first_name_address_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone_number',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
