# Generated by Django 5.0.2 on 2024-02-21 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_category_is_active_alter_profile_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='medium_image',
            field=models.ImageField(default=None, upload_to='images/medium/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='small_image',
            field=models.ImageField(default=1, upload_to='images/small/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x000001E12D5DA980>', max_length=200),
        ),
    ]
