# Generated by Django 5.0.2 on 2024-02-22 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_product_medium_image_alter_product_small_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='medium_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='small_image',
        ),
        migrations.AddField(
            model_name='product',
            name='medium_image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='small_image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x0000012D7255A980>', max_length=200),
        ),
    ]
