# Generated by Django 5.0.2 on 2024-02-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_product_medium_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='medium_image_path',
        ),
        migrations.RemoveField(
            model_name='product',
            name='small_image_path',
        ),
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x00000210DC4FA980>', max_length=200),
        ),
    ]
