# Generated by Django 5.0.2 on 2024-02-23 10:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
