# Generated by Django 5.0.2 on 2024-02-24 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_seller_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='aprroved',
            new_name='approved',
        ),
    ]
