# Generated by Django 5.0.2 on 2024-02-24 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_product_image_ratio_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='aprroved',
            new_name='approved',
        ),
    ]
