# Generated by Django 5.0.2 on 2024-03-25 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_wallet_profile_wallet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wallet',
            new_name='WalletItem',
        ),
    ]
