# Generated by Django 5.0.2 on 2024-03-29 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_delete_wallettransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_ratio',
        ),
    ]
