# Generated by Django 5.0.2 on 2024-03-29 14:23

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_ratio',
            field=image_cropping.fields.ImageRatioField('image', '400x400', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='image ratio'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=image_cropping.fields.ImageCropField(upload_to='images/'),
        ),
    ]
